---
name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare (dotnet)
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.x'

      - name: prepare (dalamud)
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile dalamud.zip
          Expand-Archive -Force dalamud.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"
          echo "APPDATA=$env:AppData" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

      - name: prebuild (dotnet restore)
        run: dotnet restore

      - name: build
        run: dotnet build --configuration Release --no-restore --nologo
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: false

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: Resonant
          path: ${{ env.APPDATA }}\XIVLauncher\devPlugins\Resonant\Resonant\latest.zip
          if-no-files-found: error

      - name: release latest
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag_name: latest
          prerelease: true
          files: ${{ env.APPDATA }}\XIVLauncher\devPlugins\Resonant\Resonant\*
          fail_on_unmatched_files: true

